apiVersion: v1
kind: Pod
metadata:
  name: nginxmutliplecont
spec:
  containers:
    - name: nginx1stcont
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: alpine2ndcont
      image: alpine:latest
      command:
        - "sleep"
        - "3600"

